services:
  - type: web
    name: backend-ecommerce
    env: java
    plan: free
    buildCommand: "./gradlew clean build"
    startCommand: "java -jar build/libs/BackendE_Commerce-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: PORT
        value: 8080
